Sprint 1/step 2
Filin1985/react-burger pull request #8
Opened 2022-11-04 13:32 UTC by Filin1985

2022-11-05 05:11 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа.
Была проделана отличная работа по рефакторингу и увеличению функционала.

### **Вы молодец!**

- Реализован функционал компонента Popup с помощью Portals;
- Реализован контент в компоненте Popup через children;

### **Но есть несколько замечаний, которые нужно исправить:**

- Поправьте работу с propTypes: Необходимо указывать .isRequired как у элемента массива, так и у самого массива в PropTypes.

- Поправьте работу с сервером, подробнее в коде.

- Исправьте логику работы модального окна.

- Исправьте ошибку в консоли: https://yadi.sk/d/bQeKg9mCyXS6IQ;

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-11-05 05:11 UTC, ArslanMustafin commented on src/components/app/App.tsx
> +    getDataApi(setIngredients)
**Надо исправить:** Запрос должен делать только запрос. Функция запрос не должна как-то влиять на стейт. Вам нужно получить результат с функции, и только потом этот результат положить в стейт.

2022-11-05 05:11 UTC, ArslanMustafin commented on src/components/app/App.tsx
> +        {(ingredients && (
**надо исправить:** А если нам придёт пустой массив?. тут лучше изнчально делать не `null`, а пустой массив. И делать проверку на length > 0.

2022-11-05 05:11 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +  })
**Надо исправить:** `data` и `type` избыточны, тут достаточно только 1 параметра `isOpen`. Поэтому можно просто написать так:

```js
const [openModal, setOpenModal] = useState(false);
```

2022-11-05 05:11 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +  )
**Можно лучше:** Лучше обернуть в `useMemo`, чтобы не было дополнительных вычислений при ререндере.

2022-11-05 05:11 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +    })
**Можно лучше:**

во многих компонентах дублируется описание PropTypes ингредиента
Лучше вынести его в отдельный файл (можно создать файл prop-types.js в корне src) и переиспользовать описание пропсов ингрединта, а не дублировать

2022-11-05 05:11 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +  ingredientsData: PropTypes.arrayOf(
**Надо исправить:**

Необходимо указывать .isRequired как у элемента массива, так и у самого массива в PropTypes.
Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
```

2022-11-05 05:11 UTC, ArslanMustafin commented on src/components/burger-constructor/order-checkout.jsx
> +const OrderCheckout = ({ setOpenModel }) => {
~~**Надо исправить:** по чек-листу у вас должен быть компонент `order-details`. И он должен лежать в папке `components`.~~

2022-11-05 05:11 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  const [openModal, setOpenModal] = useState({
**Надо исправить:** Описал похожее замечание в `burger-constructor`, но в этом случае достаточно просто поля `data`. Его также лучше вынести, и переименовать: 

```js
const [selectIngredient, setSelectIngredient] = useState(null);
```

При закрытии модального окна не забудьте обнулить `selectIngredient`.

2022-11-05 05:11 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  )
**Можно лучше:** Стоит обернуть в useMemo.

2022-11-05 05:11 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  ingredientsData: PropTypes.arrayOf(
**Надо исправить:**

Необходимо указывать .isRequired как у элемента массива, так и у самого массива в PropTypes.
Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
```

2022-11-05 05:11 UTC, ArslanMustafin commented on src/components/burger-ingredients/ingredient-type.jsx
> +          <a
**Надо исправить:** Этот блок не должен быть ссылкой.

2022-11-05 05:11 UTC, ArslanMustafin commented on src/components/burger-ingredients/ingredient-type.jsx
> +  data: PropTypes.arrayOf(
**Надо исправить:**

Необходимо указывать .isRequired как у элемента массива, так и у самого массива в PropTypes.
Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
```

2022-11-05 05:11 UTC, ArslanMustafin commented on src/components/burger-ingredients/ingredient-type.jsx
> +const IngredientType = ({ name, data, id, setOpenModel }) => {
**Можно лучше:** 

Лучше вынести в `components` и переименовать в `ingredients-category`.

2022-11-05 05:11 UTC, ArslanMustafin commented on src/components/ingredient-details/ingredient-details.jsx
> +  card: PropTypes.objectOf(
**Надо исправить:**

Необходимо указывать .isRequired как у элемента массива, так и у самого массива в PropTypes.
Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
```

2022-11-05 05:11 UTC, ArslanMustafin commented on src/components/modal/modal.jsx
> +      {isOpen ? (
**Надо исправить**

не нужно передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг

```js
{isOpen && (
    компонент открываемого попапа
)}
```

2022-11-05 05:11 UTC, ArslanMustafin commented on src/components/modal/modal.jsx
> +Modal.propTypes = {
**Надо исправить:** Нужно убрать пропсы `isOpen` и `type`. Модальное окно не должно знать об этом. Также можно добавить title, чтобы выводить вот эту информацию: https://yadi.sk/d/Gq5XPRzrahYYEQ.

2022-11-05 05:11 UTC, ArslanMustafin commented on src/components/modal-overlay/modal-overlay.jsx
> +const ModalOverlay = forwardRef((props, ref) => {
**Надо исправить:** компонент ModalOverlay просто подложка, у него не должно быть ни ref, ни children. Компонент должен иметь только 1 пропс `onClick`, в который передаётся функция для закрытия модального окна.

```jsx
export const ModalOverlay = ({ onClick }) => {
  return <div className={styles.overlay} onClick={onClick} />;
};

ModalOverlay.propTypes = {
  onClick: PropTypes.func,
};
```

2022-11-05 05:11 UTC, ArslanMustafin commented on src/components/modal/modal.jsx
> +    if (evt.keyCode === 27) {
**Надо исправить**

вынесите магическое значение 27 в именованную константу `const ECK_KEYCODE = 27`

2022-11-05 05:11 UTC, ArslanDev666 commented on src/components/modal/modal.jsx
> +  }
**Надо исправить:** лучше занести функцию в useEffect. Чтобы в случае чего, ссылка на функцию не пересоздавалась каждый ререндер.

2022-11-05 05:11 UTC, ArslanDev666 commented on src/components/modal/modal.jsx
> +    })
**Надо исправить:** тут лучше сразу передавать функцию, иначе у вас не будет сниматься обработчик событий, при размонтировании компонента: 

```js
    window.addEventListener('keydown', closeByEsc);
```

2022-11-05 05:11 UTC, ArslanDev666 commented on src/utils/api.js
> +const checkResponse = (res) => {
**Вы молодец:** Отлично, что вы реализовали проверку ответа от сервера.

2022-11-05 05:11 UTC, ArslanDev666 commented on src/components/modal/modal.jsx
> +    document.querySelector('#react-modals')
**Можно лучше:** Лучше вынести в переменную, а также вынести за пределы компонента.

2022-11-05 05:11 UTC, ArslanDev666 commented on src/components/modal/modal.jsx
> +const Modal = ({ isOpen, children, onClose, type }) => {
**Надо исправить:** Примерная структура модального окна должна быть такая: 

```js
<>
  <div className={styles.modal}>{/** ... */}</div>
  <ModalOverlay onClick={onClose} />
</>
```

2022-11-05 08:47 UTC, Filin1985 commented on src/components/burger-constructor/order-checkout.jsx
> +const OrderCheckout = ({ setOpenModel }) => {
Добрый день. Немного не понял замечание. У меня есть компонент order-details, который отвечает за popup с данными заказа (согласно чек-листу), а этот компонент я сам создал, чтобы выделить в отдельный компонент кнопку "Оформить заказ"

2022-11-05 20:40 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодец!**

- Практически все замечания с прошлого ревью были исправлены.

### **Но есть 1 замечание, которое нужно исправить:**

- Исправьте мелкие недочёты у компонента Modal.

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-11-05 20:40 UTC, ArslanDev666 commented on src/components/ingredient-details/ingredient-details.jsx
> +IngredientDetails.propTypes = {
**Можно лучше:** не стоит так сильно дробить ингредиент. Лучше передавать сразу цельный объект ингредиента.

2022-11-05 20:40 UTC, ArslanDev666 commented on src/components/app/App.tsx
> +  }
**Можно лучше:** Лучше вынести это всё в отдельный файл `utils/burger-api.js`.

2022-11-05 20:40 UTC, ArslanDev666 commented on src/components/burger-constructor/order-checkout.jsx
> +const OrderCheckout = ({ setOpenModel }) => {
Тогда это уже я не понял :( . Но в любом случае, не стоит так сильно разбивать компонент на более мелкие, а так вы молодец!, что обратно вернули этот кусок кода.

2022-11-05 20:40 UTC, ArslanDev666 commented on src/components/modal/modal.jsx
> +          !selectIngredient
**Можно лучше:** Не думаю, что стоит ради 1 стиля передавать целый объект, лучше конечно вообще не передавать) но если есть такая необходимость, то передавайте пропс со значением `boolean`, а не целый объект.

2022-11-05 20:40 UTC, ArslanDev666 commented on src/components/modal-overlay/modal-overlay.jsx
> +}
**Надо исправить:** Вы правильно исправили этот компонент в компоненте Modal. А тут видимо забыли :(

2022-11-05 20:40 UTC, ArslanDev666 commented on src/components/modal/modal.jsx
> +  useEffect(() => {
**надо исправить:** Не забудьте передать в useEffect, в качестве зависимостей пустой массив.

2022-11-06 05:48 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Все замечания с прошлого ревью были исправлены.

### **Вы молодец! Работа принята. Удачи в дальнейшем обучении!**

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

2022-11-06 05:48 UTC, ArslanDev666 commented on src/components/modal-overlay/modal-overlay.jsx
> +}
**Можно лучше:** пропс `children` лучше убрать) мы ведь его не используем.

2022-11-07 08:08 UTC, merged